import React, { createContext, useState, useContext, type ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 簡易的な翻訳マップ
const translations: Record<Language, Record<string, string>> = {
  ja: {
    'nav.home': 'ホーム',
    'nav.search': '探す',
    'nav.offers': 'オファー',
    'nav.chat': 'チャット',
    'nav.mypage': 'マイページ',
    'nav.notifications': '通知',
    'nav.favorites': 'お気に入り',
    'auth.login': 'ログイン',
    'auth.register': '新規登録',
    'header.menu': 'メニュー',
    'header.notifications': '通知',
    'landing.beta': 'ベータ版',
    'landing.hero.title': '夢とチャンスをダイレクトに繋ぐ',
    'landing.hero.subtitle': '志望者・ライバー・クリエイターと事務所が直接つながる、次世代のマッチングプラットフォーム',
    'landing.hero.talent_signup': '志望者として登録',
    'landing.hero.agency_signup': '事務所として登録',
    'landing.features.title': 'DreamBridgeが選ばれる理由',
    'landing.features.subtitle': '従来のスカウトやオーディションの常識を覆します。',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.logging_in': 'ログイン中...',
    'auth.no_account': 'アカウントをお持ちでない方は',
    'auth.from_top': 'トップページから登録してください',
    'auth.talent_signup': '志望者登録',
    'auth.agency_signup': '事務所登録',
    'auth.agree_tos': '利用規約',
    'auth.agree_and': 'および',
    'auth.agree_privacy': 'プライバシーポリシー',
    'auth.agree_to': 'に同意します。',
    'auth.signup_btn': '同意して登録する',
    'auth.sending': '送信中...',
    'auth.signup_success': '確認メールを送信しました。メール内のリンクをクリックして登録を完了してください。',
    'auth.login_error': 'ログインに失敗しました。',
    'auth.timeout_error': 'サーバーからの応答が一定時間を超えました。数分待ってから再試行してください。',
    'search.search_btn': '検索',
    'search.placeholder_talent': '名前やキーワードで検索',
    'search.placeholder_agency': '事務所名で検索',
    'search.no_results': '該当するユーザーが見つかりませんでした。',
    'genre.all': 'すべて',
    'genre.idol': 'アイドル',
    'genre.model': 'モデル',
    'genre.actor': '俳優',
    'genre.singer': '歌手',
    'genre.dancer': 'ダンサー',
    'genre.influencer': 'インフルエンサー',
    'genre.voice': '声優',
    'genre.creator': 'クリエイター',
    'genre.liver': 'ライバー',
    'genre.agency_talent': '芸能',
    'genre.agency_music': '音楽',
    'genre.agency_stage': '舞台',
    'genre.agency_movie': '映像',
    'detail.back': '戻る',
    'detail.verified': '運営認証済み',
    'detail.send_offer': 'オファーを送る',
    'detail.offered': 'オファー済み',
    'detail.offer_sent': 'オファーを送信しました！',
    'detail.restricted_offer': 'スタンダードプラン以上でオファー可能',
    'detail.bio_title': '紹介・意気込み',
    'detail.no_bio': '自己紹介文がありません。',
    'detail.specs_title': 'スペック情報',
    'detail.age': '年齢',
    'detail.height': '身長',
    'detail.hobbies': '趣味',
    'detail.skills': '特技',
    'detail.media_title': 'メディア・ポートフォリオ',
    'detail.photos': '写真',
    'detail.videos': '動画',
    'detail.audios': '音声',
    'detail.sns_title': 'SNSリンク',
    'chat.title': 'チャット',
    'chat.talk_tab': 'トーク',
    'chat.history_tab': 'オファー履歴',
    'chat.start_chat': 'チャットを開始しましょう！',
    'chat.input_placeholder': 'メッセージを入力...',
    'chat.not_found': 'チャットが見つかりませんでした。',
    'chat.no_approved_offers': '承認されたオファーがありません。',
    'fav.title': 'お気に入り一覧',
    'fav.view_detail': '詳細を見る',
    'fav.no_favs': 'お気に入りはまだありません。',
    'fav.talent_section': '志望者',
    'fav.agency_section': '事務所',
    'notif.title': '通知',
    'notif.mark_read': 'すべて既読にする',
    'notif.no_notifs': '通知はありません。',
    'offer.received_tab': '届いたオファー',
    'offer.sent_tab': '送ったオファー',
    'offer.status_approved': '承認済み',
    'offer.status_declined': '辞退済み',
    'offer.status_sent': '送信済み',
    'offer.approve_btn': '承認',
    'offer.decline_btn': '辞退',
    'offer.no_offers': 'まだオファーはありません。',
    'offer.no_sent_offers': 'まだオファーを送っていません。',
    'sub.title': 'プラン選択',
    'sub.beta_notice': 'ベータ期間：フリープラン提供中',
    'sub.beta_desc': '安全なマッチングのため、現在は制限付きのフリープランのみご利用いただけます。',
    'sub.free_plan': 'フリー',
    'sub.premium_plan': '上位表示プラン',
    'sub.agency_free': 'フリー（ベータ）',
    'sub.agency_standard': 'スタンダード',
    'sub.current_plan': '現在のプラン',
    'sub.coming_soon': '近日公開',
    'sub.payment_methods': 'お支払い方法（正式リリース後）',
    'verify.title_talent': '本人確認の申請',
    'verify.title_agency': '事務所認証の申請',
    'verify.step1': 'ステップ 1',
    'verify.step2': 'ステップ 2',
    'verify.step3': 'ステップ 3',
    'verify.next': '次へ進む',
    'verify.submit': 'この内容で申請する',
    'verify.success': '申請を完了しました',
    'pay.title': '支払い方法の設定',
    'pay.save': '設定を保存する',
    'legal.tos': '利用規約（ベータ版）',
    'legal.privacy': 'プライバシーポリシー',
    'legal.tokusho': '特定商取引法に基づく表記',
    'admin.title': '管理画面（ベータ）',
    'admin.approve': '承認する',
    'admin.unverify': '解除',
    'mypage.title': 'マイページ',
    'mypage.search_agency': '事務所を探す',
    'mypage.search_talent': '志望者を探す',
    'mypage.chat_offers': 'チャット＆オファー',
    'mypage.favorites': 'お気に入り',
    'mypage.plan_mgmt': 'プラン管理',
    'mypage.admin': '運営管理',
    'mypage.edit': '編集',
    'mypage.save': '保存',
    'mypage.cancel': 'キャンセル',
    'mypage.logout_btn': 'ログアウト',
    'mypage.share_sns': 'プロフィールをSNSでシェア',
    'mypage.share_desc': 'SNSで活動をアピールして、事務所やファンからの注目を集めましょう！',
    'mypage.share_x': 'Xでシェア',
    'mypage.share_insta': 'インスタ・その他でシェア',
    'mypage.copy_url': 'URLをコピー',
    'mypage.portfolio': 'ポートフォリオ',
    'mypage.photos': '写真集',
    'mypage.videos': '動画',
    'mypage.audios': '音声（ボイスサンプル）',
    'mypage.add': '追加',
    'mypage.delete_confirm': '削除してもよろしいですか？',
    'mypage.upload_success': 'アップロードが完了しました！',
    'mypage.save_error': '保存に失敗しました。',
    'mypage.location': '拠点',
    'mypage.age': '歳',
    'mypage.height': 'cm',
    'mypage.official_site': '公式サイト',
    'mypage.no_bio': '紹介文がありません',
    'mypage.loading': '読み込み中...',
    'search.title': '才能を探す',
    'search.placeholder': 'キーワードで検索...',
  },
  en: {
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.offers': 'Offers',
    'nav.chat': 'Chat',
    'nav.mypage': 'My Page',
    'nav.notifications': 'Notifications',
    'nav.favorites': 'Favorites',
    'auth.login': 'Log In',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.logging_in': 'Logging in...',
    'auth.no_account': "Don't have an account?",
    'auth.from_top': 'Register from the Top Page',
    'auth.talent_signup': 'Talent Registration',
    'auth.agency_signup': 'Agency Registration',
    'auth.agree_tos': 'Terms of Service',
    'auth.agree_and': 'and',
    'auth.agree_privacy': 'Privacy Policy',
    'auth.agree_to': 'I agree to the ',
    'auth.signup_btn': 'Agree and Register',
    'auth.sending': 'Sending...',
    'auth.signup_success': 'Confirmation email sent. Please click the link in the email to complete registration.',
    'auth.login_error': 'Login failed.',
    'auth.timeout_error': 'Server response timed out. Please wait a few minutes and try again.',
    'search.search_btn': 'Search',
    'search.placeholder_talent': 'Search by name or keyword',
    'search.placeholder_agency': 'Search by agency name',
    'search.no_results': 'No users found.',
    'genre.all': 'All',
    'genre.idol': 'Idol',
    'genre.model': 'Model',
    'genre.actor': 'Actor',
    'genre.singer': 'Singer',
    'genre.dancer': 'Dancer',
    'genre.influencer': 'Influencer',
    'genre.voice': 'Voice Actor',
    'genre.creator': 'Creator',
    'genre.liver': 'Liver',
    'genre.agency_talent': 'Ent.',
    'genre.agency_music': 'Music',
    'genre.agency_stage': 'Stage',
    'genre.agency_movie': 'Movie',
    'detail.back': 'Back',
    'detail.verified': 'Verified Agency',
    'detail.send_offer': 'Send Offer',
    'detail.offered': 'Offered',
    'detail.offer_sent': 'Offer sent!',
    'detail.restricted_offer': 'Upgrade to Standard Plan or higher to send offers.',
    'detail.bio_title': 'Introduction / Motivation',
    'detail.no_bio': 'No introduction text available.',
    'detail.specs_title': 'Specifications',
    'detail.age': 'Age',
    'detail.height': 'Height',
    'detail.hobbies': 'Hobbies',
    'detail.skills': 'Skills',
    'detail.media_title': 'Media / Portfolio',
    'detail.photos': 'Photos',
    'detail.videos': 'Videos',
    'detail.audios': 'Audios',
    'detail.sns_title': 'SNS Links',
    'chat.title': 'Chat',
    'chat.talk_tab': 'Talk',
    'chat.history_tab': 'Offer History',
    'chat.start_chat': "Let's start chatting!",
    'chat.input_placeholder': 'Type a message...',
    'chat.not_found': 'Chat not found.',
    'chat.no_approved_offers': 'No approved offers.',
    'fav.title': 'Favorites List',
    'fav.view_detail': 'View Detail',
    'fav.no_favs': 'No favorites yet.',
    'fav.talent_section': 'Talents',
    'fav.agency_section': 'Agencies',
    'notif.title': 'Notifications',
    'notif.mark_read': 'Mark all as read',
    'notif.no_notifs': 'No notifications.',
    'offer.received_tab': 'Received Offers',
    'offer.sent_tab': 'Sent Offers',
    'offer.status_approved': 'Approved',
    'offer.status_declined': 'Declined',
    'offer.status_sent': 'Sent',
    'offer.approve_btn': 'Approve',
    'offer.decline_btn': 'Decline',
    'offer.no_offers': 'No offers yet.',
    'offer.no_sent_offers': "You haven't sent any offers yet.",
    'sub.title': 'Select Plan',
    'sub.beta_notice': 'BETA: Free Plan Available',
    'sub.beta_desc': 'For safe matching, only a restricted Free Plan is currently available.',
    'sub.free_plan': 'Free',
    'sub.premium_plan': 'Premium Boost',
    'sub.agency_free': 'Free (Beta)',
    'sub.agency_standard': 'Standard',
    'sub.current_plan': 'Current Plan',
    'sub.coming_soon': 'Coming Soon',
    'sub.payment_methods': 'Payment Methods (Post-Release)',
    'verify.title_talent': 'Identity Verification',
    'verify.title_agency': 'Agency Verification',
    'verify.step1': 'Step 1',
    'verify.step2': 'Step 2',
    'verify.step3': 'Step 3',
    'verify.next': 'Next',
    'verify.submit': 'Submit Application',
    'verify.success': 'Application Submitted',
    'pay.title': 'Payment Settings',
    'pay.save': 'Save Settings',
    'legal.tos': 'Terms of Service (Beta)',
    'legal.privacy': 'Privacy Policy',
    'legal.tokusho': 'Specified Commercial Transactions Act',
    'admin.title': 'Admin Dashboard (Beta)',
    'admin.approve': 'Approve',
    'admin.unverify': 'Unverify',
    'mypage.title': 'My Page',
    'mypage.search_agency': 'Search Agencies',
    'mypage.search_talent': 'Search Talent',
    'mypage.chat_offers': 'Chat & Offers',
    'mypage.favorites': 'Favorites',
    'mypage.plan_mgmt': 'Plan Management',
    'mypage.admin': 'Admin Dashboard',
    'mypage.edit': 'Edit',
    'mypage.save': 'Save',
    'mypage.cancel': 'Cancel',
    'mypage.logout_btn': 'Log Out',
    'mypage.share_sns': 'Share Profile on SNS',
    'mypage.share_desc': 'Promote your activities on SNS and get noticed by agencies and fans!',
    'mypage.share_x': 'Share on X',
    'mypage.share_insta': 'Share on Insta/Others',
    'mypage.copy_url': 'Copy URL',
    'mypage.portfolio': 'Portfolio',
    'mypage.photos': 'Photos',
    'mypage.videos': 'Videos',
    'mypage.audios': 'Audios (Voice Samples)',
    'mypage.add': 'Add',
    'mypage.delete_confirm': 'Are you sure you want to delete?',
    'mypage.upload_success': 'Upload completed!',
    'mypage.save_error': 'Failed to save.',
    'mypage.location': 'Location',
    'mypage.age': 'years old',
    'mypage.height': 'cm',
    'mypage.official_site': 'Official Site',
    'mypage.no_bio': 'No introduction text',
    'mypage.loading': 'Loading...',
    'search.title': 'Find Talent',
    'search.placeholder': 'Search by keyword...',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // ブラウザの言語設定を初期値にする（デフォルトは 'ja'）
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'ja' || saved === 'en') return saved;
    return 'ja';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
