import React, { createContext, useState, useContext, type ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ja: {
    'nav.home': 'ホーム',
    'nav.search': '検索',
    'nav.favorites': 'お気に入り',
    'nav.mypage': 'マイページ',
    'nav.chat': 'チャット',
    'header.login': 'ログイン',
    'header.signup': '新規登録',
    'header.menu': 'メニュー',
    'header.notifications': '通知',
    'landing.beta': 'ベータ版公開中',
    'landing.hero.title': '夢とチャンスをダイレクトに繋ぐ',
    'landing.hero.subtitle': '志望者・ライバー・クリエイターと事務所が直接つながる、次世代のマッチングプラットフォーム',
    'landing.hero.talent_signup': '志望者として登録',
    'landing.hero.agency_signup': '事務所として登録',
    'landing.features.title': 'DreamBridgeの特徴',
    'landing.features.direct.title': 'ダイレクトな繋がり',
    'landing.features.direct.desc': '中間コストを排除し、志望者と事務所が直接コミュニケーション。',
    'landing.features.secure.title': '安心・安全の認証',
    'landing.features.secure.desc': '厳格な審査を通過した事務所のみが掲載。本人確認も徹底。',
    'auth.title_login': 'ログイン',
    'auth.title_signup': '新規登録',
    'auth.talent_signup': '志望者登録',
    'auth.agency_signup': '事務所登録',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.login_btn': 'ログイン',
    'auth.logging_in': 'ログイン中...',
    'auth.signup_btn': '同意して登録',
    'auth.sending': '送信中...',
    'auth.agree_tos': '利用規約',
    'auth.agree_and': 'および',
    'auth.agree_privacy': 'プライバシーポリシー',
    'auth.agree_to': 'に同意します。',
    'auth.login_link': '既にアカウントをお持ちの方はこちら',
    'auth.signup_link': 'アカウントをお持ちでない方はこちら',
    'auth.no_account': 'アカウントをお持ちでない方はこちら',
    'auth.from_top': 'トップページから登録',
    'auth.signup_success': '登録確認メールを送信しました。メール内のリンクをクリックして完了してください。',
    'auth.login_error': 'ログインに失敗しました',
    'auth.timeout_error': 'タイムアウトしました',
    'search.title_talent': '才能を探す',
    'search.title_agency': '事務所を探す',
    'search.placeholder_talent': '名前やジャンルで検索',
    'search.placeholder_agency': '事務所名で検索',
    'search.search_btn': '検索する',
    'search.no_results': '該当する結果が見つかりませんでした。',
    'genre.all': 'すべて',
    'genre.actor': '俳優・女優',
    'genre.model': 'モデル',
    'genre.idol': 'アイドル',
    'genre.artist': 'アーティスト',
    'genre.singer': '歌手',
    'genre.dancer': 'ダンサー',
    'genre.influencer': 'インフルエンサー',
    'genre.voice': '声優',
    'genre.creator': 'クリエイター',
    'genre.liver': 'ライバー',
    'genre.agency_talent': '芸能',
    'genre.agency_music': '音楽',
    'genre.agency_stage': '舞台',
    'genre.agency_movie': '映像',
    'detail.back': '戻る',
    'detail.verified': '運営認証済み',
    'detail.send_offer': 'オファーを送る',
    'detail.offered': 'オファー済み',
    'detail.offer_sent': 'オファーを送信しました！',
    'detail.restricted_offer': 'スタンダードプラン以上でオファー可能',
    'detail.bio_title': '紹介・意気込み',
    'detail.no_bio': '自己紹介文がありません。',
    'detail.specs_title': 'スペック情報',
    'detail.age': '年齢',
    'detail.height': '身長',
    'detail.weight': '体重',
    'detail.hobbies': '趣味',
    'detail.skills': '特技',
    'detail.media_title': 'メディア・ポートフォリオ',
    'detail.photos': '写真集',
    'detail.videos': '動画',
    'detail.audios': '音声',
    'detail.sns_title': 'SNSリンク',
    'detail.sns_instagram': 'Instagram',
    'detail.sns_x': 'X (Twitter)',
    'chat.title': 'チャット',
    'chat.talk_tab': 'トーク',
    'chat.history_tab': 'オファー履歴',
    'chat.start_chat': 'チャットを開始しましょう！',
    'chat.input_placeholder': 'メッセージを入力...',
    'chat.not_found': 'チャットが見つかりませんでした。',
    'chat.no_approved_offers': '承認されたオファーがありません。',
    'fav.title': 'お気に入り一覧',
    'fav.view_detail': '詳細を見る',
    'fav.no_favs': 'お気に入りはまだありません。',
    'fav.talent_section': '志望者',
    'fav.agency_section': '事務所',
    'notif.title': '通知',
    'notif.mark_read': 'すべて既読にする',
    'notif.no_notifs': '通知はありません。',
    'offer.received_tab': '届いたオファー',
    'offer.sent_tab': '送ったオファー',
    'offer.status_approved': '承認済み',
    'offer.status_declined': '辞退済み',
    'offer.status_sent': '送信済み',
    'offer.approve_btn': '承認',
    'offer.decline_btn': '辞退',
    'offer.no_offers': 'まだオファーはありません。',
    'offer.no_sent_offers': 'まだオファーを送っていません。',
    'sub.title': 'プラン選択',
    'sub.beta_notice': 'ベータ期間：フリープラン提供中',
    'sub.beta_desc': '安全なマッチングのため、現在は制限付きのフリープランのみご利用いただけます。',
    'sub.free_plan': 'フリー',
    'sub.premium_plan': '上位表示プラン',
    'sub.agency_free': 'フリー（ベータ）',
    'sub.agency_standard': 'スタンダード',
    'sub.current_plan': '現在のプラン',
    'sub.coming_soon': '近日公開',
    'sub.payment_methods': 'お支払い方法（正式リリース後）',
    'verify.title_talent': '本人確認の申請',
    'verify.title_agency': '事務所認証の申請',
    'verify.subtitle_talent': '信頼性向上のため、公的書類による本人確認を行っています。',
    'verify.subtitle_agency': 'なりすまし防止と信頼性向上のため、公式な認証を行っています。',
    'verify.step1': 'ステップ 1: 基本情報',
    'verify.step2': 'ステップ 2: 書類アップロード',
    'verify.step3': 'ステップ 3: 確認・完了',
    'verify.birth_date': '生年月日',
    'verify.corporate_id': '法人番号 (13桁)',
    'verify.corporate_site': '公式サイト URL',
    'verify.doc_desc_talent': '運転免許証、マイナンバーカード、パスポートのいずれかの写真をアップロードしてください。',
    'verify.doc_desc_agency': '履歴事項全部証明書（3ヶ月以内に発行されたもの）の写真をアップロードしてください。',
    'verify.id_label': '身分証明書 (免許証・パスポート等)',
    'verify.business_label': '営業許可証・登記簿など',
    'verify.upload_box': 'ファイルを選択、またはドラッグ＆ドロップ',
    'verify.upload_hint': 'PDF, JPG, PNG (最大 10MB)',
    'verify.review_title': '最終確認',
    'verify.review_name_talent': '氏名',
    'verify.review_name_agency': '社名・事務所名',
    'verify.review_doc': '提出書類',
    'verify.warning': '虚偽の申請はアカウント停止の対象となります。提出された書類は本人確認以外の目的で使用されることはありません。',
    'verify.next': '次へ進む',
    'verify.submit': 'この内容で申請する',
    'verify.success': '申請を完了しました',
    'verify.success_desc': '運営チームにて内容を確認しております。通常1〜3営業日以内に結果をご案内いたします。',
    'verify.pending': '審査中です。完了まで数日かかる場合があります。',
    'pay.title': '支払い方法の設定',
    'pay.save': '設定を保存する',
    'legal.tos': '利用規約（ベータ版）',
    'legal.privacy': 'プライバシーポリシー',
    'legal.tokusho': '特定商取引法に基づく表記',
    'admin.title': '管理画面（ベータ）',
    'admin.subtitle': '事務所ユーザーの認証と安全管理',
    'admin.approve': '承認する',
    'admin.unverify': '解除',
    'admin.th_name': '事務所名 / ID',
    'admin.th_location': '場所 / SNS',
    'admin.th_status': '現在のステータス',
    'admin.th_actions': '操作',
    'admin.status_unverified': '未認証',
    'admin.no_pending': '承認待ちの申請はありません。',
    'admin.no_agencies': '登録されている事務所はありません。',
    'admin.update_success': '更新しました',
    'admin.update_fail': '更新に失敗しました',
    'admin.revoke_success': '認証を解除しました',
    'mypage.title': 'マイページ',
    'mypage.search_agency': '事務所を探す',
    'mypage.search_talent': '志望者を探す',
    'mypage.chat_offers': 'チャット＆オファー',
    'mypage.favorites': 'お気に入り',
    'mypage.plan_mgmt': 'プラン管理',
    'mypage.admin': '運営管理',
    'mypage.edit': '編集',
    'mypage.save': '保存',
    'mypage.cancel': 'キャンセル',
    'mypage.logout_btn': 'ログアウト',
    'mypage.share_sns': 'プロフィールをSNSでシェア',
    'mypage.share_desc': 'SNSで活動をアピールして、事務所やファンからの注目を集めましょう！',
    'mypage.share_x': 'Xでシェア',
    'mypage.share_insta': 'インスタ・その他でシェア',
    'mypage.copy_url': 'URLをコピー',
    'mypage.portfolio': 'ポートフォリオ',
    'mypage.photos': '写真集',
    'mypage.videos': '動画',
    'mypage.audios': '音声（ボイスサンプル）',
    'mypage.add': '追加',
    'mypage.delete_confirm': '削除してもよろしいですか？',
    'mypage.upload_success': 'アップロードが完了しました！',
    'mypage.save_error': '保存に失敗しました。',
    'mypage.location': '拠点',
    'mypage.age': '歳',
    'mypage.height': 'cm',
    'mypage.weight': 'kg',
    'mypage.official_site': '公式サイト',
    'mypage.no_bio': '紹介文がありません',
    'mypage.loading': '読み込み中...',
    'mypage.no_name': '名前未設定',
    'mypage.not_set': '未設定',
    'mypage.genres': 'ジャンル',
    'mypage.full_name': '氏名',
    'mypage.agency_name': '事務所名',
    'mypage.location_label': '活動拠点',
    'mypage.hq_label': '本社所在地',
    'mypage.bio_placeholder_talent': '自己紹介・意気込み',
    'mypage.bio_placeholder_agency': '事務所紹介・募集要項',
    'mypage.website_url': '公式サイトURL',
    'search.title': '才能を探す',
    'search.placeholder': 'キーワードで検索...',
  },
  en: {
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.favorites': 'Favorites',
    'nav.mypage': 'My Page',
    'nav.chat': 'Chat',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.menu': 'Menu',
    'header.notifications': 'Notifications',
    'landing.beta': 'Beta Live',
    'landing.hero.title': 'Direct Connection for Dreams',
    'landing.hero.subtitle': 'Next-gen matching platform for talent and agencies.',
    'landing.hero.talent_signup': 'Sign Up as Talent',
    'landing.hero.agency_signup': 'Sign Up as Agency',
    'landing.features.title': 'Features of DreamBridge',
    'landing.features.direct.title': 'Direct Connection',
    'landing.features.direct.desc': 'Communicate directly with agencies without intermediate costs.',
    'landing.features.secure.title': 'Secure Verification',
    'landing.features.secure.desc': 'Only agencies passed strict screening are listed.',
    'auth.title_login': 'Login',
    'auth.title_signup': 'Sign Up',
    'auth.from_top': 'Register from the Top Page',
    'auth.talent_signup': 'Talent Registration',
    'auth.agency_signup': 'Agency Registration',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.login_btn': 'Login',
    'auth.logging_in': 'Logging in...',
    'auth.signup_btn': 'Agree and Register',
    'auth.sending': 'Sending...',
    'auth.agree_tos': 'Terms of Service',
    'auth.agree_and': 'and',
    'auth.agree_privacy': 'Privacy Policy',
    'auth.agree_to': 'I agree to the ',
    'auth.login_link': 'Already have an account? Login here',
    'auth.signup_link': 'Don\'t have an account? Sign up here',
    'auth.no_account': 'Don\'t have an account? Sign up from the top page.',
    'auth.signup_success': 'Confirmation email sent. Please click the link in the email to complete registration.',
    'auth.login_error': 'Login failed',
    'auth.timeout_error': 'Server response timed out. Please wait a few minutes and try again.',
    'search.title_talent': 'Find Talent',
    'search.title_agency': 'Find Agencies',
    'search.placeholder_talent': 'Search by name or genre',
    'search.placeholder_agency': 'Search by agency name',
    'search.search_btn': 'Search',
    'search.no_results': 'No results found.',
    'genre.all': 'All',
    'genre.actor': 'Actor',
    'genre.model': 'Model',
    'genre.idol': 'Idol',
    'genre.artist': 'Artist',
    'genre.singer': 'Singer',
    'genre.dancer': 'Dancer',
    'genre.influencer': 'Influencer',
    'genre.voice': 'Voice',
    'genre.creator': 'Creator',
    'genre.liver': 'Liver',
    'genre.agency_talent': 'Ent.',
    'genre.agency_music': 'Music',
    'genre.agency_stage': 'Stage',
    'genre.agency_movie': 'Movie',
    'detail.back': 'Back',
    'detail.verified': 'Verified Agency',
    'detail.send_offer': 'Send Offer',
    'detail.offered': 'Offered',
    'detail.offer_sent': 'Offer sent successfully!',
    'detail.restricted_offer': 'Upgrade to Standard Plan or higher to send offers.',
    'detail.bio_title': 'Introduction / Motivation',
    'detail.no_bio': 'No introduction text available.',
    'detail.specs_title': 'Specifications',
    'detail.age': 'Age',
    'detail.height': 'Height',
    'detail.weight': 'Weight',
    'detail.hobbies': 'Hobbies',
    'detail.skills': 'Skills',
    'detail.media_title': 'Media / Portfolio',
    'detail.photos': 'Photos',
    'detail.videos': 'Videos',
    'detail.audios': 'Audios',
    'detail.sns_title': 'SNS Links',
    'detail.sns_instagram': 'Instagram',
    'detail.sns_x': 'X (Twitter)',
    'chat.title': 'Chat',
    'chat.talk_tab': 'Talk',
    'chat.history_tab': 'Offer History',
    'chat.start_chat': 'Start a conversation!',
    'chat.input_placeholder': 'Type a message...',
    'chat.not_found': 'Chat not found.',
    'chat.no_approved_offers': 'No approved offers.',
    'fav.title': 'Favorites',
    'fav.view_detail': 'View Details',
    'fav.no_favs': 'No favorites yet.',
    'fav.talent_section': 'Talent',
    'fav.agency_section': 'Agencies',
    'notif.title': 'Notifications',
    'notif.mark_read': 'Mark all as read',
    'notif.no_notifs': 'No notifications.',
    'offer.received_tab': 'Received',
    'offer.sent_tab': 'Sent',
    'offer.status_approved': 'Approved',
    'offer.status_declined': 'Declined',
    'offer.status_sent': 'Sent',
    'offer.approve_btn': 'Approve',
    'offer.decline_btn': 'Decline',
    'offer.no_offers': 'No offers yet.',
    'offer.no_sent_offers': 'No offers sent yet.',
    'sub.title': 'Select Plan',
    'sub.beta_notice': 'Beta Period: Free Plan Available',
    'sub.beta_desc': 'During beta, only limited free plans are available for secure matching.',
    'sub.free_plan': 'Free',
    'sub.premium_plan': 'Premium',
    'sub.agency_free': 'Free (Beta)',
    'sub.agency_standard': 'Standard',
    'sub.current_plan': 'Current Plan',
    'sub.coming_soon': 'Coming Soon',
    'sub.payment_methods': 'Payment Methods (Post-release)',
    'verify.title_talent': 'Talent Verification',
    'verify.title_agency': 'Agency Verification',
    'verify.subtitle_talent': 'We perform identity verification using official documents to improve trust.',
    'verify.subtitle_agency': 'We perform official verification to prevent impersonation and improve reliability.',
    'verify.step1': 'Step 1: Basic Info',
    'verify.step2': 'Step 2: Upload Documents',
    'verify.step3': 'Step 3: Confirm',
    'verify.birth_date': 'Birth Date',
    'verify.corporate_id': 'Corporate ID (13 digits)',
    'verify.corporate_site': 'Official Website URL',
    'verify.doc_desc_talent': 'Please upload a photo of your Driver\'s License, My Number Card, or Passport.',
    'verify.doc_desc_agency': 'Please upload a photo of your Certificate of Registered Matters (issued within 3 months).',
    'verify.id_label': 'Identification (License/Passport)',
    'verify.business_label': 'Business License/Registry',
    'verify.upload_box': 'Select file or drag & drop',
    'verify.upload_hint': 'PDF, JPG, PNG (Max 10MB)',
    'verify.review_title': 'Final Review',
    'verify.review_name_talent': 'Full Name',
    'verify.review_name_agency': 'Company Name',
    'verify.review_doc': 'Submitted Document',
    'verify.warning': 'Providing false information may result in account suspension. Submitted documents will not be used for any purpose other than verification.',
    'verify.next': 'Next',
    'verify.submit': 'Submit Application',
    'verify.success': 'Application Submitted',
    'verify.success_desc': 'Our team is currently reviewing your information. Usually, we will notify you of the results within 1-3 business days.',
    'verify.pending': 'Under review. It may take a few days.',
    'pay.title': 'Payment Settings',
    'pay.save': 'Save Settings',
    'legal.tos': 'Terms of Service (Beta)',
    'legal.privacy': 'Privacy Policy',
    'legal.tokusho': 'Commercial Transactions Law',
    'admin.title': 'Admin (Beta)',
    'admin.subtitle': 'Agency User Verification & Safety Management',
    'admin.approve': 'Approve',
    'admin.unverify': 'Unverify',
    'admin.th_name': 'Agency Name / ID',
    'admin.th_location': 'Location / SNS',
    'admin.th_status': 'Current Status',
    'admin.th_actions': 'Actions',
    'admin.status_unverified': 'Unverified',
    'admin.no_pending': 'No pending applications.',
    'admin.no_agencies': 'No agencies registered yet.',
    'admin.update_success': 'Updated successfully',
    'admin.update_fail': 'Update failed',
    'admin.revoke_success': 'Verification revoked',
    'mypage.title': 'My Page',
    'mypage.search_agency': 'Search Agencies',
    'mypage.search_talent': 'Search Talent',
    'mypage.chat_offers': 'Chat & Offers',
    'mypage.favorites': 'Favorites',
    'mypage.plan_mgmt': 'Plan Management',
    'mypage.admin': 'Admin Dashboard',
    'mypage.edit': 'Edit',
    'mypage.save': 'Save',
    'mypage.cancel': 'Cancel',
    'mypage.logout_btn': 'Log Out',
    'mypage.share_sns': 'Share Profile on SNS',
    'mypage.share_desc': 'Promote your activities on SNS and get noticed by agencies and fans!',
    'mypage.share_x': 'Share on X',
    'mypage.share_insta': 'Share on Insta/Others',
    'mypage.copy_url': 'Copy URL',
    'mypage.portfolio': 'Portfolio',
    'mypage.photos': 'Photos',
    'mypage.videos': 'Videos',
    'mypage.audios': 'Audios',
    'mypage.add': 'Add',
    'mypage.delete_confirm': 'Are you sure you want to delete?',
    'mypage.upload_success': 'Upload completed!',
    'mypage.save_error': 'Failed to save.',
    'mypage.location': 'Location',
    'mypage.age': 'years old',
    'mypage.height': 'cm',
    'mypage.weight': 'kg',
    'mypage.official_site': 'Official Site',
    'mypage.no_bio': 'No introduction text',
    'mypage.loading': 'Loading...',
    'mypage.no_name': 'No Name',
    'mypage.not_set': 'Not set',
    'mypage.genres': 'Genres',
    'mypage.full_name': 'Full Name',
    'mypage.agency_name': 'Agency Name',
    'mypage.location_label': 'Location',
    'mypage.hq_label': 'Headquarters',
    'mypage.bio_placeholder_talent': 'Bio / Motivation',
    'mypage.bio_placeholder_agency': 'Agency description / Requirements',
    'mypage.website_url': 'Official Website URL',
    'search.title': 'Find Talent',
    'search.placeholder': 'Search by keyword...',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
