import React, { createContext, useState, useContext, type ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ja: {
    'nav.home': 'ホーム',
    'nav.search': '検索',
    'nav.favorites': 'お気に入り',
    'nav.mypage': 'マイページ',
    'nav.chat': 'チャット',
    'header.login': 'ログイン',
    'header.signup': '新規登録',
    'header.menu': 'メニュー',
    'header.notifications': '通知',
    'landing.beta': 'ベータ版公開中',
    'landing.hero.title': '夢とチャンスをダイレクトに繋ぐ',
    'landing.hero.subtitle': 'どこにいても、才能は届く。志望者・タレントと事務所・制作会社をダイレクトにつなぐ、日本初のプラットフォーム',
    'landing.hero.talent_signup': '志望者として登録',
    'landing.hero.agency_signup': '事務所として登録',
    'landing.features.title': 'DreamBridgeが選ばれる理由',
    'landing.features.subtitle': '従来のスカウトやオーディションの常識を覆します。',
    'landing.features.direct.title': 'ダイレクトオファー',
    'landing.features.direct.desc': '事務所・制作会社からあなたへ直接オファーが届く。中間業者不要で、全国どこにいてもチャンスをつかめる。',
    'landing.features.secure.title': '安心・安全の認証制度',
    'landing.features.secure.desc': '登録事務所・制作会社は運営が厳重に審査。未成年の方も保護者の同意システムで安心して活動できます。',
    'landing.features.location.title': 'どこにいても使える',
    'landing.features.location.desc': '地方にいながら全国の事務所・制作会社とつながれる。上京不要で、あなたの夢に近づける場所がここにある。',
    'landing.cta.title': '今すぐベータ版に参加',
    'landing.cta.desc': '現在、全ての機能を無料でご利用いただけます。この機会にぜひベータ版をお試しください。',
    'landing.cta.btn': '無料で登録を始める',
    'footer.desc': '夢とチャンスをダイレクトに繋ぐマッチングプラットフォーム',
    'auth.title_login': 'ログイン',
    'auth.title_signup': '新規登録',
    'auth.login': 'ログイン',
    'auth.signup': '新規登録',
    'auth.talent_signup': '志望者登録',
    'auth.agency_signup': '事務所登録',
    'auth.casting_signup': 'キャスティング会社登録',
    'auth.company_name': '会社名',
    'auth.representative_name': '担当者名',
    'auth.business_content': '事業内容',
    'auth.contact_info': '連絡先',
    'auth.past_works': '過去の制作実績（作品名・公開URLなど）',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.login_btn': 'ログイン',
    'auth.logging_in': 'ログイン中...',
    'auth.signup_btn': '同意して登録',
    'auth.sending': '送信中...',
    'auth.agree_tos': '利用規約',
    'auth.agree_and': 'および',
    'auth.agree_privacy': 'プライバシーポリシー',
    'auth.agree_to': 'に同意します。',
    'auth.login_link': '既にアカウントをお持ちの方はこちら',
    'auth.signup_link': 'アカウントをお持ちでない方はこちら',
    'auth.no_account': 'アカウントをお持ちでない方はこちら',
    'auth.from_top': 'トップページから登録',
    'auth.minor_consent': '【未成年の方へ】保護者の同意を得て登録していますか？',
    'auth.signup_success': '登録確認メールを送信しました。メール内のリンクをクリックして完了してください。',
    'auth.login_error': 'ログインに失敗しました',
    'auth.timeout_error': 'タイムアウトしました。しばらく時間をおいて再度お試しください（スリープ中のデータベースの起動に1分程度かかる場合があります）。',
    'auth.invitation_title': '事務所招待からの登録',
    'auth.invitation_invalid': '無効な招待状または期限切れです。',
    'auth.forgot_password': 'パスワードをお忘れですか？',
    'auth.reset_password_desc': '登録済みのメールアドレスを入力してください。パスワード再設定用のリンクをお送りします。',
    'auth.reset_password_btn': '再設定メールを送る',
    'auth.reset_email_sent': '再設定用のメールを送信しました。メール内のリンクからパスワードを再設定してください。',
    'auth.reset_password_title': '新しいパスワードの設定',
    'auth.new_password': '新しいパスワード',
    'auth.confirm_new_password': '新しいパスワード（確認）',
    'auth.reset_password_success': 'パスワードを再設定しました。',
    'auth.reset_password_too_short': 'パスワードは6文字以上で入力してください。',
    'auth.reset_password_mismatch': 'パスワードが一致しません。',
    'search.title_talent': '才能を探す',
    'search.title_agency': '事務所を探す',
    'search.title_casting': '制作・広告会社を探す',
    'search.placeholder_talent': '名前やジャンルで検索',
    'search.placeholder_agency': '事務所名で検索',
    'search.search_btn': '検索する',
    'search.no_results': '該当する結果が見つかりませんでした。',
    'search.filter_open': '▼ 詳細フィルターを表示',
    'search.filter_close': '▲ フィルターを閉じる',
    'search.gender': '性別',
    'search.gender_male': '男性',
    'search.gender_female': '女性',
    'search.gender_other': 'その他',
    'search.affiliation_only': '未所属のみ',
    'search.age_range': '年齢範囲',
    'search.height_range': '身長範囲 (cm)',
    'search.min': '最小',
    'search.max': '最大',
    'search.location_all': 'すべての地域',
    'search.clear': 'クリア',
    'search.sort_by': '並び替え',
    'search.sort_newest': '登録が新しい順',
    'search.sort_updated': '更新順',
    'search.sort_verified': '認証済み優先',
    'search.weight_range': '体重範囲 (kg)',
    'search.skill_tag': 'スキルタグ',
    'genre.all': 'すべて',
    'genre.actor': '俳優・女優',
    'genre.model': 'モデル',
    'genre.idol': 'アイドル',
    'genre.artist': 'アーティスト',
    'genre.singer': '歌手',
    'genre.dancer': 'ダンサー',
    'genre.influencer': 'インフルエンサー',
    'genre.voice': '声優',
    'genre.creator': 'クリエイター',
    'genre.liver': 'ライバー',
    'genre.agency_talent': '芸能',
    'genre.agency_music': '音楽',
    'genre.agency_stage': '舞台',
    'genre.agency_movie': '映像',
    'genre.production': '制作・広告',
    'genre.comedy': 'お笑い',
    'genre.announcer': 'アナウンサー',
    'genre.intellectual': '文化人',
    'genre.athlete': 'スポーツ選手',
    'genre.mc': 'MC',
    'genre.narrator': 'ナレーター',
    'genre.movie': '映画',
    'genre.drama': 'ドラマ',
    'genre.cm': 'CM',
    'genre.web_ad': 'Web広告',
    'genre.magazine': '雑誌',
    'genre.event': 'イベント',
    'skill.actor': '俳優',
    'skill.voice': '声優',
    'skill.stage': '舞台',
    'skill.fashion': 'ファッション',
    'skill.ads': '広告',
    'skill.gravure': 'グラビア',
    'skill.singer': '歌手',
    'skill.idol': 'アイドル',
    'skill.band': 'バンド',
    'skill.liver': 'ライバー',
    'skill.youtuber': 'YouTuber',
    'skill.tiktoker': 'TikToker',
    'skill.dancer': 'ダンサー',
    'skill.comedy': 'お笑い',
    'skill.announcer': 'アナウンサー',
    'common.age_suffix': '歳',
    'common.gender_male': '男性',
    'common.gender_female': '女性',
    'common.gender_other': 'その他',
    'common.gender_none': '未設定',
    'common.status_reviewing': '審査中',
    'landing.audience_title': 'あらゆる才能と機会を募集中',
    'landing.genre.talent_agency': '芸能事務所',
    'mypage.category_acting': '演技系',
    'mypage.category_model': 'モデル系',
    'mypage.category_music': '音楽系',
    'mypage.category_streaming': '配信系',
    'mypage.category_other': 'その他',
    'mypage.skill_multi_notice': '(複数選択可)',
    'admin.seed_success_msg': 'サンプルデータを投入しました',
    'admin.seed_error_msg': 'データ投入中にエラーが発生しました',
    'detail.back': '戻る',
    'detail.verified': '運営認証済み',
    'detail.skill_verified': 'スキル確認済み',
    'detail.send_offer': 'オファーを送る',
    'detail.select_job_label': 'どの案件のスカウトですか？',
    'detail.select_job_none': '特に案件なし（自由スカウト）',
    'detail.offered': 'オファー済み',
    'detail.offer_sent': 'オファーを送信しました！',
    'detail.offer_mediated_sent': '事務所経由でオファーを送信しました。事務所の承認をお待ちください。',
    'detail.limit_reached': '今月のオファー送信上限（3件）に達しました。',
    'detail.limit_reached_btn': '上限に達しました',
    'detail.limit_reached_desc': '今月のオファー上限（3件）に達しています',
    'detail.offer_stopped': 'オファー受付停止中',
    'detail.offer_stopped_desc': 'このタレントは現在オファーを受け付けていません',
    'detail.offer_via_agency': '事務所経由でオファー',
    'detail.affiliated_with': '所属',
    'detail.restricted_offer': 'スタンダードプラン以上でオファー可能',
    'detail.bio_title_talent': '自己紹介・実績',
    'detail.bio_title_agency': '実績・特徴',
    'detail.no_bio': '自己紹介文がありません。',
    'detail.specs_title': 'スペック情報',
    'detail.age': '年齢',
    'detail.height': '身長',
    'detail.weight': '体重',
    'detail.hobbies': '趣味',
    'detail.skills': '特技',
    'detail.media_title': 'メディア・ポートフォリオ',
    'detail.photos': '写真集',
    'detail.videos': '動画',
    'detail.audios': '音声',
    'detail.sns_title': 'SNSリンク',
    'detail.sns_instagram': 'Instagram',
    'detail.sns_x': 'X (Twitter)',
    'chat.title': 'チャット',
    'chat.talk_tab': 'トーク',
    'chat.history_tab': 'オファー履歴',
    'chat.start_chat': 'チャットを開始しましょう！',
    'chat.input_placeholder': 'メッセージを入力...',
    'chat.not_found': 'チャットが見つかりませんでした。',
    'chat.no_approved_offers': '承認されたオファーがありません。',
    'chat.delete_btn': 'チャットを削除',
    'chat.delete_confirm': 'このチャットを削除しますか？自分の画面からのみ削除され、相手には引き続き表示されます。',
    'chat.deal_not_confirmed': 'この案件はまだ成立していません',
    'chat.deal_confirm_prompt': 'この案件が実際に成立したことを確定しますか？相手側も確定すると「成立」になります。',
    'chat.deal_confirm_btn': '案件成立にする',
    'chat.deal_confirmed_waiting': '成立を確定しました。相手の確認を待っています。',
    'chat.deal_confirmed_both': 'この案件は成立しました',
    'chat.deal_confirm_fail': '確定に失敗しました。時間をおいて再度お試しください。',
    'chat.mediated_badge': '3者チャット',
    'chat.mediated_info': '担当事務所: {agency} | {casting} & {talent}',
    'chat.read': '既読',
    'chat.curfew_notice': '【深夜の利用について】18歳未満の方は、22:00から05:00の間のチャット利用は控えることを推奨します。',
    'fav.title': 'お気に入り一覧',
    'fav.view_detail': '詳細を見る',
    'fav.no_favs': 'お気に入りはまだありません。',
    'fav.talent_section': '志望者',
    'fav.agency_section': '事務所',
    'notif.title': '通知',
    'notif.mark_read': 'すべて既読にする',
    'notif.no_notifs': '通知はありません。',
    'pay.title': '支払い方法の設定',
    'pay.save': '設定を保存する',
    'pay.card_holder': 'カード名義',
    'pay.card_number': 'カード番号',
    'pay.expiry': '有効期限',
    'pay.cvv': 'セキュリティコード',
    'pay.methods_desc': '月額プランのお支払いに使用するカード情報を登録します。',
    'job.no_jobs': '現在、掲載中の案件はありません。',
    'nav.offers': 'オファー管理',
    'offer.received_tab': '届いたチャット依頼',
    'offer.sent_tab': '送ったチャット依頼',
    'offer.status_approved': 'チャット開始',
    'offer.status_declined': '今回は見送り',
    'offer.status_sent': '送信済み',
    'offer.approve_btn': 'チャットを開始する',
    'offer.decline_btn': '今回は見送る',
    'offer.no_offers': 'まだチャット依頼はありません。',
    'offer.no_sent_offers': 'まだチャット依頼を送っていません。',
    'scout.approve_btn': '詳しく話を聞く（チャット開始）',
    'scout.decline_btn': '今回は見送る',
    'direct_offer.approve_btn': 'チャットで詳細を確認',
    'direct_offer.decline_btn': '今回は見送る',
    'agency_offer.approve_btn': '案件用チャットを開設',
    'agency_offer.decline_btn': '今回は見送る',
    'sub.title': 'プラン選択',
    'sub.beta_notice': 'ベータ期間：フリープラン提供中',
    'sub.beta_desc': '安全なマッチングのため、現在は制限付きのフリープランのみご利用いただけます。',
    'sub.free_plan': 'フリー',
    'sub.premium_plan': '上位表示プラン',
    'sub.agency_free': 'フリー（ベータ）',
    'sub.agency_standard': 'スタンダード',
    'sub.current_plan': '現在のプラン',
    'sub.coming_soon': '近日公開',
    'sub.payment_methods': 'お支払い方法（正式リリース後）',
    'sub.feature_profile': 'プロフィール作成',
    'sub.feature_receive_offers': 'オファーの受信',
    'sub.feature_chat_unlimited': 'チャットし放題',
    'sub.feature_offers_limit': '月3件までのオファー',
    'sub.feature_talent_search': 'タレント検索',
    'sub.feature_chat_basic': '基本チャット',
    'verify.title_talent': '本人確認（タレント）',
    'verify.title_agency': '事務所認証の申請',
    'verify.subtitle_talent': '信頼性向上のため、公的書類による本人確認を行っています。',
    'verify.subtitle_agency': 'なりすまし防止と信頼性向上のため、公式な認証を行っています。',
    'verify.step1': 'ステップ 1: 基本情報',
    'verify.step2': 'ステップ 2: 書類アップロード',
    'verify.step3': 'ステップ 3: 確認・完了',
    'verify.birth_date': '生年月日',
    'verify.corporate_id': '法人番号 (13桁)',
    'verify.corporate_site': '公式サイト URL',
    'verify.doc_desc_talent': '運転免許証、マイナンバーカード、パスポートのいずれかの写真をアップロードしてください。',
    'verify.doc_desc_agency': '履歴事項全部証明書（3ヶ月以内に発行されたもの）の写真をアップロードしてください。',
    'verify.id_label': '身分証明書 (免許証・パスポート等)',
    'verify.business_label': '営業許可証・登記簿など',
    'verify.upload_box': 'ファイルを選択、またはドラッグ＆ドロップ',
    'verify.upload_hint': 'PDF, JPG, PNG (最大 10MB)',
    'verify.review_title': '最終確認',
    'verify.review_name_talent': '氏名',
    'verify.review_name_agency': '社名・事務所名',
    'verify.review_doc': '提出書類',
    'verify.warning': '虚偽の申請はアカウント停止の対象となります。提出された書類は本人確認以外の目的で使用されることはありません。',
    'verify.next': '次へ進む',
    'verify.submit': 'この内容で申請する',
    'verify.success': '申請を完了しました',
    'verify.success_desc': '運営チームにて内容を確認しております。通常1〜3営業日以内に結果をご案内いたします。',
    'verify.pending': '審査中です。完了まで数日かかる場合があります。',
    'verify.minor_notice': '【未成年の方】保護者の同意が必要です',
    'verify.parent_name': '保護者氏名',
    'verify.parent_contact': '保護者の連絡先 (電話番号/メール)',
    'verify.upload_complete': 'アップロード完了',
    'verify.review_parent_name': '保護者名',
    'verify.review_parent_contact': '保護者連絡先',
    'verify.not_completed': '未完了',
    'safety.report_btn': '通報する',
    'safety.report_title': 'ユーザーを通報',
    'safety.report_reason': '通報の理由',
    'safety.reason_inappropriate': '不適切なコンテンツ・勧誘',
    'safety.reason_harassment': '嫌がらせ・迷惑行為',
    'safety.reason_scam': '詐欺・虚偽の情報',
    'safety.reason_offline': '強引な密室での対面要求',
    'safety.reason_lesson_fee': 'レッスン料等の金銭要求',
    'safety.reason_other': 'その他',
    'safety.report_desc': '詳細内容（具体的なやり取りなど）',
    'safety.report_submit': '通報を送信',
    'safety.report_success': '通報を運営に送信しました。ご協力ありがとうございます。',
    'safety.minor_warning_title': '【安全のためのご注意】',
    'safety.minor_warning_body': '未成年の方は、初めて会う際は必ず保護者に同伴してもらうか、公共の場所を選んでください。密室での面談や、過度な個人情報の要求には注意し、不審な点があればすぐに通報してください。',
    'legal.tos': '利用規約（ベータ版）',
    'legal.privacy': 'プライバシーポリシー',
    'legal.tokusho': '特定商取引法に基づく表記',
    'legal.beta_notice_title': '【ベータ版提供に関するお知らせ】',
    'legal.beta_notice_body': '現在、DreamBridgeはベータ版として提供されています。ベータ版の提供期間中、全ての機能を無料でご利用いただけますが、一部の機能制限や予告ない仕様変更、データのリセット等が行われる可能性があります。あらかじめご了承ください。',
    'admin.title': '管理画面（ベータ）',
    'admin.subtitle': '事務所ユーザーの認証と安全管理',
    'admin.approve': '承認する',
    'admin.unverify': '解除',
    'admin.th_name': '事務所名 / ID',
    'admin.th_location': '場所 / SNS',
    'admin.th_status': '現在のステータス',
    'admin.th_actions': '操作',
    'admin.status_unverified': '未認証',
    'admin.no_pending': '承認待ちの申請はありません。',
    'admin.no_agencies': '登録されている事務所はありません。',
    'admin.update_success': '更新しました',
    'admin.update_fail': '更新に失敗しました',
    'admin.revoke_success': '認証を解除しました',
    'admin.seed_data': 'サンプルデータ投入',
    'admin.seed_success': 'サンプルデータを投入しました',
    'admin.seed_error': 'データ投入中にエラーが発生しました',
    'admin.tab_pending': '承認待ち',
    'admin.tab_agencies': '事務所',
    'admin.tab_casting': '制作・広告',
    'admin.th_id': '申請者 / ID',
    'admin.th_type': '種類 / 担当者',
    'admin.th_detail': '詳細 / 書類',
    'admin.th_actions_row': '操作',
    'admin.biz_content': '事業内容',
    'admin.contact': '連絡先',
    'admin.view_doc': '書類を確認する',
    'admin.parent': '保護者',
    'admin.approve_btn': '承認',
    'admin.reject_btn': '却下',
    'admin.no_data': 'データはありません。',
    'mypage.title': 'マイページ',
    'mypage.search_agency': '事務所を探す',
    'mypage.search_talent': '志望者を探す',
    'mypage.chat_offers': 'チャット＆オファー',
    'mypage.favorites': 'お気に入り',
    'mypage.plan_mgmt': 'プラン管理',
    'mypage.admin': '運営管理',
    'mypage.edit': '編集',
    'mypage.save': '保存',
    'mypage.cancel': 'キャンセル',
    'mypage.logout_btn': 'ログアウト',
    'mypage.share_sns': 'プロフィールをSNSでシェア',
    'mypage.share_desc': 'SNSで活動をアピールして、事務所やファンからの注目を集めましょう！',
    'mypage.share_x': 'Xでシェア',
    'mypage.share_insta': 'インスタ・その他でシェア',
    'mypage.copy_url': 'URLをコピー',
    'mypage.portfolio': 'ポートフォリオ',
    'mypage.photos': '写真集',
    'mypage.videos': '動画',
    'mypage.audios': '音声（ボイスサンプル）',
    'mypage.add': '追加',
    'mypage.delete_confirm': '削除してもよろしいですか？',
    'mypage.delete_account': '退会する',
    'mypage.delete_account_confirm': '本当に退会しますか？プロフィール情報（写真・自己紹介・SNSなど）はすべて削除され、この操作は元に戻せません。',
    'mypage.deleted_user_name': '退会したユーザー',
    'mypage.upload_success': 'アップロードが完了しました！',
    'mypage.save_error': '保存に失敗しました。',
    'mypage.coming_soon_official': '正式リリース時に開放予定',
    'mypage.gender': '性別',
    'mypage.gender_male': '男性',
    'mypage.gender_female': '女性',
    'mypage.gender_other': 'その他',
    'mypage.gender_none': '未設定',
    'mypage.reviewing': '審査中',
    'mypage.multiple_select': '(複数選択可)',
    'mypage.share_text': 'DreamBridgeで活動中！プロフィールをチェックしてね！\n',
    'mypage.share_insta_alert': 'URLをコピーしました！インスタのストーリーなどに貼り付けてください。',
    'mypage.share_copy_alert': 'プロフィールURLをコピーしました！',
    'mypage.location': '拠点',
    'mypage.age': '歳',
    'mypage.height': 'cm',
    'mypage.weight': 'kg',
    'mypage.official_site': '公式サイト',
    'mypage.no_bio': '紹介文がありません',
    'mypage.no_videos': '動画はありません。',
    'mypage.no_audios': '音声サンプルはありません。',
    'mypage.loading': '読み込み中...',
    'mypage.profile_load_error': 'プロフィール情報の読み込みに時間がかかっています。通信環境をご確認のうえ、もう一度お試しください。',
    'mypage.retry': '再読み込み',
    'mypage.no_name': '名前未設定',
    'mypage.not_set': '未設定',
    'mypage.genres': 'ジャンル',
    'mypage.affiliation': '所属状況',
    'mypage.skills': 'スキルタグ',
    'mypage.affiliated': '事務所所属中',
    'mypage.skill_review_request': 'スキル確認を申請する',
    'mypage.skill_review_reapply': '再度スキル確認を申請する',
    'mypage.skill_review_pending': 'スキル確認 審査中です',
    'mypage.skill_review_requested': 'スキル確認を申請しました。運営の審査をお待ちください。',
    'mypage.freelance': 'フリーランス',
    'mypage.full_name': '氏名',
    'mypage.agency_name': '事務所名',
    'mypage.location_label': '活動拠点',
    'mypage.hq_label': '本社所在地',
    'mypage.bio_placeholder_talent': '自己紹介・実績',
    'mypage.bio_placeholder_agency': '実績・特徴',
    'mypage.talent_mgmt': '所属タレント管理',
    'mypage.talent_mgmt_desc': '所属タレントの登録・管理・案件承認を行います。',
    'mypage.unaffiliated': '未所属',
    'mypage.website_url': '公式サイトURL',
    'agency.invite_new': '新規タレント招待',
    'agency.tab_talents': '所属タレント',
    'agency.tab_invitations': '招待中',
    'agency.tab_offers': '外部承認',
    'agency.th_talent_name': 'タレント名',
    'agency.th_genre': 'ジャンル',
    'agency.th_accept_job': '案件受付',
    'agency.th_ops': '操作',
    'agency.no_talents': '所属タレントはいません。',
    'agency.accepting': '受付中',
    'agency.stopped': '停止中',
    'agency.detail': '詳細',
    'agency.th_name': '名前',
    'agency.th_email': 'メールアドレス',
    'agency.th_invite_date': '招待日',
    'agency.th_invite_link': '招待リンク',
    'agency.no_invitations': '待機中の招待はありません。',
    'agency.copy_link': 'リンクをコピー',
    'agency.copy_success': '招待リンクをコピーしました。',
    'agency.no_pending_offers': '現在承認待ちのオファーはありません。',
    'agency.offer_from_casting': '制作会社からのオファー',
    'agency.target_talent': '対象タレント',
    'agency.approve_btn': 'チャットを開設する',
    'agency.reject_btn': '今回は見送る',
    'agency.company_profile': '会社プロフィール',
    'agency.invite_modal_title': 'タレントを招待する',
    'agency.invite_name_label': 'タレント名',
    'agency.invite_email_label': 'メールアドレス',
    'agency.invite_genre_label': '主なジャンル',
    'agency.invite_creating': '作成中...',
    'agency.invite_create_btn': '招待状を作成',
    'agency.invite_success': '招待状を作成しました。リンクをコピーしてタレントに送ってください。',
    'agency.invite_fail': '招待に失敗しました',
    'agency.offer_approved_msg': 'チャットを開設しました。',
    'agency.offer_rejected_msg': '今回は見送りました。',
    'search.title': '才能を探す',
    'search.placeholder': 'キーワードで検索...',
    'job.title': '求人・案件一覧',
    'job.search': 'キーワードで案件を検索...',
    'job.management': '案件・求人管理',
    'job.subtitle': 'あなたの才能を活かせる案件を見つけましょう。',
    'job.need_login': 'ログインが必要です。',
    'job.only_talent': 'タレントのみ応募可能です。',
    'job.already_applied': '既に応募済みです。',
    'job.already_applied_btn': '応募済み',
    'job.apply': '応募する',
    'job.applying': '応募中...',
    'job.apply_fail': '応募に失敗しました',
    'job.apply_success': '応募が完了しました！',
    'offer.send_fail': 'オファーの送信に失敗しました。',
    'offer.send_success': 'オファーを送信しました！',
    'offer.send_confirm': 'このタレントにオファーを送りますか？',
    'offer.for_job': '対象案件',
    'offer.schedule_prompt': '案件実施日を入力してください',
    'offer.schedule_confirm': '確定',
    'offer.schedule_cancel': 'キャンセル',
    'offer.schedule_required': '予定日を入力してください',
    'detail.attendance_score': '信頼スコア',
    'attendance.survey_question': '相手は予定通り対応しましたか？',
    'attendance.survey_attended': 'はい、対応しました',
    'attendance.survey_no_show': 'いいえ、来ませんでした',
    'attendance.survey_thanks': 'ご回答ありがとうございました。',
    'attendance.survey_invalid': 'このアンケートは既に回答済みか、期限が切れています。',
    'attendance.survey_error': '回答の送信に失敗しました。もう一度お試しください。',
    'job.restricted_talent': '事務所所属のタレントは直接応募できません。事務所の担当者にご相談ください。',
    'job.select_talent_first': '応募させるタレントを選択してください。',
    'job.select_talent_placeholder': '応募させるタレントを選択',
    'job.apply_on_behalf': '代理応募する',
    'job.filter_area_reward': 'エリア・報酬',
    'job.filter_all_locations': 'すべての地域',
    'job.filter_reward_placeholder': '報酬で絞り込み (例: 30,000)',
    'job.filter_skill_genre': 'スキル・ジャンル',
    'job.filter_clear': 'フィルターをクリア',
    'job.recruiting': '募集中',
    'job.reward_label': '報酬',
    'job.location_label': '場所',
    'job.deadline_label': '期限',
    'job.view_detail': '詳細を見る',
    'job.post': '案件を投稿',
    'job.post_title': '案件を投稿する',
    'job.form_title': '案件タイトル',
    'job.form_reward': '報酬',
    'job.form_location': '場所',
    'job.form_deadline': '応募期限',
    'job.form_description': '案件の詳細説明',
    'job.form_tags_label': '必要なスキルタグ (複数選択)',
    'job.posting': '投稿中...',
    'job.post_btn': '投稿する',
    'job.post_fail': '投稿に失敗しました',
    'job.post_success': '案件を投稿しました！',
    'job.manage_tab_posted': '投稿した案件',
    'job.manage_tab_applicants': '応募者一覧',
    'job.manage_no_jobs': '投稿した案件はありません。',
    'job.manage_status': 'ステータス',
    'job.manage_recruiting': '募集中',
    'job.manage_ended': '終了',
    'job.manage_stop_btn': '手動で終了する',
    'job.manage_restart_btn': '募集を再開する',
    'job.manage_detail_btn': '詳細確認',
    'job.manage_no_applicants': '現在応募はありません。',
    'job.manage_target_job': '対象案件',
    'job.manage_status_pending': '検討中',
    'job.manage_status_approved': 'チャット開始',
    'job.manage_status_rejected': '今回は見送り',
    'job.manage_profile_btn': 'プロフィール確認',
    'job.manage_approve_btn': 'チャットを開始する',
    'job.manage_approve_btn_agency': '面談を調整する（チャット開始）',
    'job.manage_approve_btn_casting': '事務所とのチャットを開始する',
    'job.manage_approve_btn_free': 'チャットで選考・相談を進める',
    'job.manage_reject_btn': '今回は見送る',
    'job.manage_chat_btn': 'チャットへ',
    'job.manage_update_fail': '更新に失敗しました',
    'job.manage_approve_success': 'チャットを開始できるようになりました。',
    'job.manage_reject_success': '辞退の処理を完了しました。',
    'job.manage_chat_welcome': 'チャットの開設が承認されました。こちらから詳細を相談しましょう。',
    'job.app_subtitle': '応募した案件の選考状況を確認できます。',
    'job.app_no_apps': 'まだ応募した案件はありません。',
    'job.app_find_btn': '案件を探す',
    'job.app_status_approved': 'チャット開始',
    'job.app_status_rejected': '今回は見送り',
    'job.app_status_pending': '選考中',
    'job.app_date_label': '応募日',
    'job.app_chat_btn': 'チャットへ',
    'job.app_detail_btn': '詳細',
    'job.application_list': '応募した案件一覧',
  },
  en: {
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.favorites': 'Favorites',
    'nav.mypage': 'My Page',
    'nav.chat': 'Chat',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.menu': 'Menu',
    'header.notifications': 'Notifications',
    'landing.beta': 'Beta Live',
    'landing.hero.title': 'Connecting Dreams and Opportunities Directly',
    'landing.hero.subtitle': 'Talent reaches everywhere. Japan\'s first platform connecting talents and agencies/studios directly.',
    'landing.hero.talent_signup': 'Sign Up as Talent',
    'landing.hero.agency_signup': 'Sign Up as Agency',
    'landing.features.title': 'Why DreamBridge?',
    'landing.features.subtitle': 'Revolutionizing traditional scouting and auditions.',
    'landing.features.direct.title': 'Direct Offers',
    'landing.features.direct.desc': 'Get offers directly from agencies and studios. No middlemen, seize opportunities from anywhere nationwide.',
    'landing.features.secure.title': 'Safe & Secure Verification',
    'landing.features.secure.desc': 'All registered agencies are strictly screened. Minors can active safely with our parental consent system.',
    'landing.features.location.title': 'Usable Anywhere',
    'landing.features.location.desc': 'Connect with nationwide agencies while staying in your local area. No need to move to Tokyo to reach your dreams.',
    'landing.cta.title': 'Join the Beta Now',
    'landing.cta.desc': 'Currently, all features are free to use. Take this opportunity to try the beta version.',
    'landing.cta.btn': 'Start Free Registration',
    'footer.desc': 'Directly connecting dreams and opportunities.',
    'auth.title_login': 'Login',
    'auth.title_signup': 'Sign Up',
    'auth.from_top': 'Register from the Top Page',
    'auth.minor_consent': '[For Minors] Do you have parental consent to register?',
    'auth.talent_signup': 'Talent Registration',
    'auth.agency_signup': 'Agency Registration',
    'auth.casting_signup': 'Casting Co. Registration',
    'auth.company_name': 'Company Name',
    'auth.representative_name': 'Contact Person',
    'auth.business_content': 'Business Content',
    'auth.contact_info': 'Contact Info',
    'auth.past_works': 'Past Works (titles, public URLs, etc.)',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.login_btn': 'Login',
    'auth.logging_in': 'Logging in...',
    'auth.signup_btn': 'Agree and Register',
    'auth.sending': 'Sending...',
    'auth.agree_tos': 'Terms of Service',
    'auth.agree_and': 'and',
    'auth.agree_privacy': 'Privacy Policy',
    'auth.agree_to': 'I agree to the ',
    'auth.login_link': 'Already have an account? Login here',
    'auth.signup_link': 'Don\'t have an account? Sign up here',
    'auth.no_account': 'Don\'t have an account? Sign up from the top page.',
    'auth.signup_success': 'Confirmation email sent. Please click the link in the email to complete registration.',
    'auth.login_error': 'Login failed',
    'auth.timeout_error': 'Server response timed out. Please wait a few minutes and try again.',
    'auth.forgot_password': 'Forgot your password?',
    'auth.reset_password_desc': 'Enter your registered email address and we\'ll send you a password reset link.',
    'auth.reset_password_btn': 'Send reset link',
    'auth.reset_email_sent': 'A reset link has been sent to your email. Please follow the link to set a new password.',
    'auth.reset_password_title': 'Set a new password',
    'auth.new_password': 'New password',
    'auth.confirm_new_password': 'Confirm new password',
    'auth.reset_password_success': 'Your password has been reset.',
    'auth.reset_password_too_short': 'Password must be at least 6 characters.',
    'auth.reset_password_mismatch': 'Passwords do not match.',
    'auth.invitation_title': 'Register from Agency Invitation',
    'auth.invitation_invalid': 'Invalid or expired invitation.',
    'search.title_talent': 'Find Talent',
    'search.title_agency': 'Find Agencies',
    'search.title_casting': 'Find Studios & Casting',
    'search.placeholder_talent': 'Search by name or genre',
    'search.placeholder_agency': 'Search by agency name',
    'search.search_btn': 'Search',
    'search.no_results': 'No results found.',
    'search.filter_open': '▼ Show detailed filters',
    'search.filter_close': '▲ Close filters',
    'search.gender': 'Gender',
    'search.gender_male': 'Male',
    'search.gender_female': 'Female',
    'search.gender_other': 'Other',
    'search.affiliation_only': 'Unaffiliated only',
    'search.age_range': 'Age Range',
    'search.height_range': 'Height Range (cm)',
    'search.min': 'Min',
    'search.max': 'Max',
    'search.location_all': 'All Regions',
    'search.clear': 'Clear',
    'search.sort_by': 'Sort by',
    'search.sort_newest': 'Newest',
    'search.sort_updated': 'Recently Updated',
    'search.sort_verified': 'Verified First',
    'search.weight_range': 'Weight Range (kg)',
    'search.skill_tag': 'Skill Tag',
    'genre.all': 'All',
    'genre.actor': 'Actor',
    'genre.model': 'Model',
    'genre.idol': 'Idol',
    'genre.artist': 'Artist',
    'genre.singer': 'Singer',
    'genre.dancer': 'Dancer',
    'genre.influencer': 'Influencer',
    'genre.voice': 'Voice',
    'genre.creator': 'Creator',
    'genre.liver': 'Liver',
    'genre.agency_talent': 'Ent.',
    'genre.agency_music': 'Music',
    'genre.agency_stage': 'Stage',
    'genre.agency_movie': 'Movie',
    'genre.production': 'Production/Ads',
    'genre.comedy': 'Comedy',
    'genre.announcer': 'Announcer',
    'genre.intellectual': 'Intellectual',
    'genre.athlete': 'Athlete',
    'genre.mc': 'MC',
    'genre.narrator': 'Narrator',
    'genre.movie': 'Movie',
    'genre.drama': 'Drama',
    'genre.cm': 'CM',
    'genre.web_ad': 'Web Ad',
    'genre.magazine': 'Magazine',
    'genre.event': 'Event',
    'skill.actor': 'Actor',
    'skill.voice': 'Voice',
    'skill.stage': 'Stage',
    'skill.fashion': 'Fashion',
    'skill.ads': 'Ads',
    'skill.gravure': 'Gravure',
    'skill.singer': 'Singer',
    'skill.idol': 'Idol',
    'skill.band': 'Band',
    'skill.liver': 'Liver',
    'skill.youtuber': 'YouTuber',
    'skill.tiktoker': 'TikToker',
    'skill.dancer': 'Dancer',
    'skill.comedy': 'Comedy',
    'skill.announcer': 'Announcer',
    'common.age_suffix': ' years old',
    'common.gender_male': 'Male',
    'common.gender_female': 'Female',
    'common.gender_other': 'Other',
    'common.gender_none': 'Not Set',
    'common.status_reviewing': 'Reviewing',
    'landing.audience_title': 'Recruiting all talents and opportunities',
    'landing.genre.talent_agency': 'Talent Agency',
    'mypage.category_acting': 'Acting',
    'mypage.category_model': 'Modeling',
    'mypage.category_music': 'Music',
    'mypage.category_streaming': 'Streaming',
    'mypage.category_other': 'Others',
    'mypage.skill_multi_notice': '(Multiple choices allowed)',
    'admin.seed_success_msg': 'Sample data seeded successfully',
    'admin.seed_error_msg': 'Error occurred during data seeding',
    'detail.back': 'Back',
    'detail.verified': 'Verified Agency',
    'detail.skill_verified': 'Skill Verified',
    'detail.send_offer': 'Send Offer',
    'detail.select_job_label': 'Which job is this scout for?',
    'detail.select_job_none': 'No specific job (general scout)',
    'detail.offered': 'Offered',
    'detail.offer_sent': 'Offer sent successfully!',
    'detail.offer_mediated_sent': 'Offer sent via agency. Please wait for agency approval.',
    'detail.limit_reached': 'Monthly offer limit (3) reached.',
    'detail.limit_reached_btn': 'Limit Reached',
    'detail.limit_reached_desc': 'Monthly offer limit (3) has been reached.',
    'detail.offer_stopped': 'Offers Paused',
    'detail.offer_stopped_desc': 'This talent is currently not accepting offers.',
    'detail.offer_via_agency': 'Offer via Agency',
    'detail.affiliated_with': 'Affiliated',
    'detail.restricted_offer': 'Upgrade to Standard Plan or higher to send offers.',
    'detail.bio_title_talent': 'About Me / Achievements',
    'detail.bio_title_agency': 'Achievements / Characteristics',
    'detail.no_bio': 'No introduction text available.',
    'detail.specs_title': 'Specifications',
    'detail.age': 'Age',
    'detail.height': 'Height',
    'detail.weight': 'Weight',
    'detail.hobbies': 'Hobbies',
    'detail.skills': 'Skills',
    'detail.media_title': 'Media / Portfolio',
    'detail.photos': 'Photos',
    'detail.videos': 'Videos',
    'detail.audios': 'Audios',
    'detail.sns_title': 'SNS Links',
    'detail.sns_instagram': 'Instagram',
    'detail.sns_x': 'X (Twitter)',
    'chat.title': 'Chat',
    'chat.talk_tab': 'Talk',
    'chat.history_tab': 'Offer History',
    'chat.start_chat': 'Start a conversation!',
    'chat.input_placeholder': 'Type a message...',
    'chat.not_found': 'Chat not found.',
    'chat.no_approved_offers': 'No approved offers.',
    'chat.delete_btn': 'Delete chat',
    'chat.delete_confirm': 'Delete this chat? It will only be removed from your own view -- the other party will still see it.',
    'chat.deal_not_confirmed': 'This job has not been confirmed yet',
    'chat.deal_confirm_prompt': 'Confirm that this job actually happened? It becomes "confirmed" once the other party confirms too.',
    'chat.deal_confirm_btn': 'Confirm job',
    'chat.deal_confirmed_waiting': 'You confirmed it. Waiting for the other party to confirm too.',
    'chat.deal_confirmed_both': 'This job has been confirmed',
    'chat.deal_confirm_fail': 'Failed to confirm. Please try again later.',
    'chat.curfew_notice': '[Late Night Usage] For users under 18, it is recommended to avoid using chat between 22:00 and 05:00.',
    'fav.title': 'Favorites',
    'fav.view_detail': 'View Details',
    'fav.no_favs': 'No favorites yet.',
    'fav.talent_section': 'Talent',
    'fav.agency_section': 'Agencies',
    'notif.title': 'Notifications',
    'notif.mark_read': 'Mark all as read',
    'notif.no_notifs': 'No notifications.',
    'offer.received_tab': 'Received Chat Requests',
    'offer.sent_tab': 'Sent Chat Requests',
    'offer.status_approved': 'Chat Started',
    'offer.status_declined': 'Passed',
    'offer.status_sent': 'Sent',
    'offer.approve_btn': 'Start Chat',
    'offer.decline_btn': 'Pass',
    'scout.approve_btn': 'Hear more (Start Chat)',
    'scout.decline_btn': 'Pass',
    'direct_offer.approve_btn': 'Check details via Chat',
    'direct_offer.decline_btn': 'Pass',
    'agency_offer.approve_btn': 'Open Chat for Project',
    'agency_offer.decline_btn': 'Pass',
    'offer.no_offers': 'No chat requests yet.',
    'offer.no_sent_offers': 'No chat requests sent yet.',
    'offer.send_fail': 'Failed to send offer.',
    'offer.send_success': 'Offer sent!',
    'offer.send_confirm': 'Send an offer to this talent?',
    'offer.for_job': 'For job',
    'offer.schedule_prompt': 'Please enter the job execution date',
    'offer.schedule_confirm': 'Confirm',
    'offer.schedule_cancel': 'Cancel',
    'offer.schedule_required': 'Please enter a scheduled date',
    'detail.attendance_score': 'Trust Score',
    'attendance.survey_question': 'Did the other party show up as scheduled?',
    'attendance.survey_attended': 'Yes, they showed up',
    'attendance.survey_no_show': 'No, they did not show up',
    'attendance.survey_thanks': 'Thank you for your response.',
    'attendance.survey_invalid': 'This survey has already been answered or has expired.',
    'attendance.survey_error': 'Failed to submit your response. Please try again.',
    'sub.title': 'Select Plan',
    'sub.beta_notice': 'Beta Period: Free Plan Available',
    'sub.beta_desc': 'During beta, only limited free plans are available for secure matching.',
    'sub.free_plan': 'Free',
    'sub.premium_plan': 'Premium',
    'sub.agency_free': 'Free (Beta)',
    'sub.agency_standard': 'Standard',
    'sub.current_plan': 'Current Plan',
    'sub.coming_soon': 'Coming Soon',
    'sub.payment_methods': 'Payment Methods (Post-release)',
    'sub.feature_profile': 'Profile Creation',
    'sub.feature_receive_offers': 'Receive Offers',
    'sub.feature_chat_unlimited': 'Unlimited Chat',
    'sub.feature_offers_limit': 'Up to 3 offers/mo',
    'sub.feature_talent_search': 'Talent Search',
    'sub.feature_chat_basic': 'Basic Chat',
    'verify.title_talent': 'Talent Verification',
    'verify.title_agency': 'Agency Verification',
    'verify.subtitle_talent': 'We perform identity verification using official documents to improve trust.',
    'verify.subtitle_agency': 'We perform official verification to prevent impersonation and improve reliability.',
    'verify.step1': 'Step 1: Basic Info',
    'verify.step2': 'Step 2: Upload Documents',
    'verify.step3': 'Step 3: Confirm',
    'verify.birth_date': 'Birth Date',
    'verify.corporate_id': 'Corporate ID (13 digits)',
    'verify.corporate_site': 'Official Website URL',
    'verify.doc_desc_talent': 'Please upload a photo of your Driver\'s License, My Number Card, or Passport.',
    'verify.doc_desc_agency': 'Please upload a photo of your Certificate of Registered Matters (issued within 3 months).',
    'verify.id_label': 'Identification (License/Passport)',
    'verify.business_label': 'Business License/Registry',
    'verify.upload_box': 'Select file or drag & drop',
    'verify.upload_hint': 'PDF, JPG, PNG (Max 10MB)',
    'verify.review_title': 'Final Review',
    'verify.review_name_talent': 'Full Name',
    'verify.review_name_agency': 'Company Name',
    'verify.review_doc': 'Submitted Document',
    'verify.warning': 'Providing false information may result in account suspension. Submitted documents will not be used for any purpose other than verification.',
    'verify.next': 'Next',
    'verify.submit': 'Submit Application',
    'verify.success': 'Application Submitted',
    'verify.success_desc': 'Our team is currently reviewing your information. Usually, we will notify you of the results within 1-3 business days.',
    'verify.pending': 'Under review. It may take a few days.',
    'verify.minor_notice': '[For Minors] Parental consent is required',
    'verify.parent_name': 'Parent Name',
    'verify.parent_contact': 'Parent Contact (Phone/Email)',
    'verify.upload_complete': 'Upload Complete',
    'verify.review_parent_name': 'Parent Name',
    'verify.review_parent_contact': 'Parent Contact',
    'verify.not_completed': 'Not Completed',
    'pay.title': 'Payment Settings',
    'pay.save': 'Save Settings',
    'safety.report_btn': 'Report User',
    'safety.report_title': 'Report User',
    'safety.report_reason': 'Reason for Reporting',
    'safety.reason_inappropriate': 'Inappropriate Content / Solicitation',
    'safety.reason_harassment': 'Harassment / Nuisance',
    'safety.reason_scam': 'Scam / False Information',
    'safety.reason_offline': 'Forcing Offline Meetings in Private',
    'safety.reason_lesson_fee': 'Demanding Lesson Fees or Payment',
    'safety.reason_other': 'Other',
    'safety.report_desc': 'Details (Specific messages, etc.)',
    'safety.report_submit': 'Submit Report',
    'safety.report_success': 'Report submitted to administrators. Thank you for your cooperation.',
    'safety.minor_warning_title': '[Safety Notice]',
    'safety.minor_warning_body': 'For minors: Always have a parent accompany you when meeting for the first time, or choose a public place. Be cautious of meetings in private rooms or excessive requests for personal information. Report immediately if you notice anything suspicious.',
    'legal.tos': 'Terms of Service (Beta)',
    'legal.privacy': 'Privacy Policy',
    'legal.tokusho': 'Commercial Transactions Law',
    'legal.beta_notice_title': '[Notice regarding Beta version]',
    'legal.beta_notice_body': 'Currently, DreamBridge is provided as a beta version. All features are free to use during the beta period, but there may be functional limitations, specification changes without notice, and data resets. Please be aware of this in advance.',
    'admin.title': 'Admin (Beta)',
    'admin.subtitle': 'Agency User Verification & Safety Management',
    'admin.approve': 'Approve',
    'admin.unverify': 'Unverify',
    'admin.th_name': 'Agency Name / ID',
    'admin.th_location': 'Location / SNS',
    'admin.th_status': 'Current Status',
    'admin.th_actions': 'Actions',
    'admin.status_unverified': 'Unverified',
    'admin.no_pending': 'No pending applications.',
    'admin.no_agencies': 'No agencies registered yet.',
    'admin.update_success': 'Updated successfully',
    'admin.update_fail': 'Update failed',
    'admin.revoke_success': 'Verification revoked',
    'admin.seed_data': 'Seed Sample Data',
    'admin.seed_success': 'Sample data seeded successfully',
    'admin.seed_error': 'Error occurred during data seeding',
    'admin.tab_pending': 'Pending',
    'admin.tab_agencies': 'Agencies',
    'admin.tab_casting': 'Studios',
    'admin.th_id': 'Applicant / ID',
    'admin.th_type': 'Type / Contact',
    'admin.th_detail': 'Detail / Docs',
    'admin.th_actions_row': 'Actions',
    'admin.biz_content': 'Business',
    'admin.contact': 'Contact',
    'admin.view_doc': 'View Document',
    'admin.parent': 'Parent',
    'admin.approve_btn': 'Approve',
    'admin.reject_btn': 'Reject',
    'admin.no_data': 'No data available.',
    'mypage.title': 'My Page',
    'mypage.search_agency': 'Search Agencies',
    'mypage.search_talent': 'Search Talent',
    'mypage.chat_offers': 'Chat & Offers',
    'mypage.favorites': 'Favorites',
    'mypage.plan_mgmt': 'Plan Management',
    'mypage.admin': 'Admin Dashboard',
    'mypage.edit': 'Edit',
    'mypage.save': 'Save',
    'mypage.cancel': 'Cancel',
    'mypage.logout_btn': 'Log Out',
    'mypage.share_sns': 'Share Profile on SNS',
    'mypage.share_desc': 'Promote your activities on SNS and get noticed by agencies and fans!',
    'mypage.share_x': 'Share on X',
    'mypage.share_insta': 'Share on Insta/Others',
    'mypage.copy_url': 'Copy URL',
    'mypage.portfolio': 'Portfolio',
    'mypage.photos': 'Photos',
    'mypage.videos': 'Videos',
    'mypage.audios': 'Audios',
    'mypage.add': 'Add',
    'mypage.delete_confirm': 'Are you sure you want to delete?',
    'mypage.delete_account': 'Delete account',
    'mypage.delete_account_confirm': 'Are you sure you want to delete your account? All profile information (photos, bio, social links, etc.) will be removed, and this cannot be undone.',
    'mypage.deleted_user_name': 'Deleted user',
    'mypage.upload_success': 'Upload completed!',
    'mypage.save_error': 'Failed to save.',
    'mypage.coming_soon_official': 'Coming soon at official release',
    'mypage.location': 'Location',
    'mypage.age': 'years old',
    'mypage.height': 'cm',
    'mypage.weight': 'kg',
    'mypage.official_site': 'Official Site',
    'mypage.no_bio': 'No introduction text',
    'mypage.no_videos': 'No videos yet.',
    'mypage.no_audios': 'No audio samples yet.',
    'mypage.loading': 'Loading...',
    'mypage.profile_load_error': 'Your profile is taking a while to load. Please check your connection and try again.',
    'mypage.retry': 'Retry',
    'mypage.no_name': 'No Name',
    'mypage.not_set': 'Not set',
    'mypage.genres': 'Genres',
    'mypage.affiliation': 'Affiliation Status',
    'mypage.skills': 'Skill Tags',
    'mypage.talent_mgmt': 'Talent Management',
    'mypage.talent_mgmt_desc': 'Register, manage, and approve jobs for your talents.',
    'mypage.unaffiliated': 'Unaffiliated',
    'mypage.affiliated': 'Affiliated',
    'mypage.skill_review_request': 'Request Skill Review',
    'mypage.skill_review_reapply': 'Reapply for Skill Review',
    'mypage.skill_review_pending': 'Skill review pending',
    'mypage.skill_review_requested': 'Skill review requested. Please wait for the review.',
    'mypage.freelance': 'Freelance',
    'mypage.full_name': 'Full Name',
    'mypage.agency_name': 'Agency Name',
    'mypage.location_label': 'Location',
    'mypage.hq_label': 'Headquarters',
    'mypage.bio_placeholder_talent': 'Bio / Achievements',
    'mypage.bio_placeholder_agency': 'Achievements / Characteristics',
    'mypage.website_url': 'Official Website URL',
    'agency.invite_new': 'Invite New Talent',
    'agency.tab_talents': 'Affiliated Talents',
    'agency.tab_invitations': 'Inviting',
    'agency.tab_offers': 'Mediated Offers',
    'agency.th_talent_name': 'Talent Name',
    'agency.th_genre': 'Genre',
    'agency.th_accept_job': 'Accept Jobs',
    'agency.th_ops': 'Actions',
    'agency.no_talents': 'No affiliated talents yet.',
    'agency.accepting': 'Accepting',
    'agency.stopped': 'Stopped',
    'agency.detail': 'Detail',
    'agency.th_name': 'Name',
    'agency.th_email': 'Email',
    'agency.th_invite_date': 'Invite Date',
    'agency.th_invite_link': 'Invite Link',
    'agency.no_invitations': 'No pending invitations.',
    'agency.copy_link': 'Copy Link',
    'agency.copy_success': 'Invite link copied to clipboard.',
    'agency.no_pending_offers': 'No offers waiting for approval.',
    'agency.offer_from_casting': 'Offer from Studio',
    'agency.target_talent': 'Target Talent',
    'agency.approve_btn': 'Approve',
    'agency.reject_btn': 'Reject',
    'agency.company_profile': 'Company Profile',
    'agency.invite_modal_title': 'Invite Talent',
    'agency.invite_name_label': 'Talent Name',
    'agency.invite_email_label': 'Email',
    'agency.invite_genre_label': 'Main Genres',
    'agency.invite_creating': 'Creating...',
    'agency.invite_create_btn': 'Create Invitation',
    'agency.invite_success': 'Invitation created. Please copy the link and send it to the talent.',
    'agency.invite_fail': 'Failed to invite',
    'agency.offer_approved_msg': 'Offer approved. 3-party chat started.',
    'agency.offer_rejected_msg': 'Offer rejected.',
    'search.title': 'Find Talent',
    'search.placeholder': 'Search by keyword...',
    'job.title': 'Jobs',
    'job.search': 'Search jobs by keyword...',
    'job.subtitle': 'Find jobs that make the most of your talent.',
    'job.need_login': 'Login required.',
    'job.only_talent': 'Only talent can apply.',
    'job.already_applied': 'Already applied.',
    'job.already_applied_btn': 'Applied',
    'job.apply': 'Apply',
    'job.applying': 'Applying...',
    'job.apply_fail': 'Failed to apply',
    'job.apply_success': 'Application submitted successfully!',
    'job.select_talent_first': 'Please select a talent to apply on behalf of.',
    'job.select_talent_placeholder': 'Select talent to apply for',
    'job.apply_on_behalf': 'Apply on Behalf',
    'job.filter_area_reward': 'Area & Reward',
    'job.filter_all_locations': 'All Regions',
    'job.filter_reward_placeholder': 'Filter by reward (e.g. 30,000)',
    'job.filter_skill_genre': 'Skills & Genres',
    'job.filter_clear': 'Clear Filters',
    'job.recruiting': 'Recruiting',
    'job.reward_label': 'Reward',
    'job.location_label': 'Location',
    'job.deadline_label': 'Deadline',
    'job.view_detail': 'View Details',
    'job.post': 'Post a Job',
    'job.post_title': 'Post a Job',
    'job.form_title': 'Job Title',
    'job.form_reward': 'Reward',
    'job.form_location': 'Location',
    'job.form_deadline': 'Deadline',
    'job.form_description': 'Description',
    'job.form_tags_label': 'Required Skill Tags (Multiple)',
    'job.posting': 'Posting...',
    'job.post_btn': 'Post',
    'job.post_fail': 'Failed to post',
    'job.post_success': 'Job posted successfully!',
    'job.manage_tab_posted': 'Posted Jobs',
    'job.manage_tab_applicants': 'Applicants',
    'job.manage_no_jobs': 'No jobs posted yet.',
    'job.manage_status': 'Status',
    'job.manage_recruiting': 'Recruiting',
    'job.manage_ended': 'Ended',
    'job.manage_stop_btn': 'Stop Manually',
    'job.manage_restart_btn': 'Restart Recruitment',
    'job.manage_detail_btn': 'Details',
    'job.manage_no_applicants': 'No applicants yet.',
    'job.manage_target_job': 'Target Job',
    'job.manage_status_pending': 'Pending',
    'job.manage_status_approved': 'Chat Started',
    'job.manage_status_rejected': 'Passed',
    'job.manage_profile_btn': 'Profile',
    'job.manage_approve_btn': 'Start Chat',
    'job.manage_approve_btn_agency': 'Adjust Interview (Start Chat)',
    'job.manage_approve_btn_casting': 'Start Chat with Agency',
    'job.manage_approve_btn_free': 'Proceed with Screening via Chat',
    'job.manage_reject_btn': 'Pass',
    'job.manage_chat_btn': 'To Chat',
    'job.manage_update_fail': 'Update failed',
    'job.manage_approve_success': 'Chat is now available.',
    'job.manage_reject_success': 'Declined.',
    'job.manage_chat_welcome': 'The chat has been opened. Let\'s discuss the details here.',
    'job.app_subtitle': 'Check the status of the jobs you applied for.',
    'job.app_no_apps': 'No applications yet.',
    'job.app_find_btn': 'Find Jobs',
    'job.app_status_approved': 'Chat Started',
    'job.app_status_rejected': 'Passed',
    'job.app_status_pending': 'Under Review',
    'job.app_date_label': 'Applied Date',
    'job.app_chat_btn': 'To Chat',
    'job.app_detail_btn': 'Detail',
    'job.application_list': 'Application List',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
